import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      suppressHydrationWarning
    >
      <meta name="viewport" content="width=device-width initial-scale=1.0" />
      <body className="min-h-full flex flex-col">
        <ThemeProvider enableSystem={false}>
          <Header />
          <p className="my-16 self-center sm:text-3xl md:text-5xl lg:text-7xl font-semibold">
            Hello, world
          </p>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
